#exec chromium-browser --kiosk file:///home/projects/HorusSoftware/splashScreen.html
#chromium-browser --start-maximized  --kiosk --use-fake-ui-for-media-stream --ignore-certificate-errors --disable-restore-session-state --no-first-run --touch-events=enabled --fast --fast-start --disable-popup-blocking --disable-infobars --disable-session-crashed-bubble --disable-tab-switcher --disable-translate --enable-low-res-tiling file:///home/projects/HorusSoftware/splashScreen.html
#chromium-browser --noerrdialogs --kiosk --start-maximized  --disable-restore-session-state  file:///home/projects/HorusSoftware/splashScreen.html --incognito
chromium-browser https://chrome.google.com/webstore/detail/flip-this/donljlliiecjcagcenoeohjmabfegkph?hl=en 


